In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../database/db.sqlite')

df = pd.read_sql("SELECT * FROM projetos", conn)



df.head()

,cdCartaConsulta,nmProjeto,sgProjeto,nmSetor,nmSujeito,Regiao,nmUnidadeFederal,nmAbrangenciaNacional,TipoFinanciamento,sgFonte,...,dtAprovDiretoria,dtAprovacaoSenado,nuResolucaoSenado,dtAssinatura,nuoperacao,dtPrimeiraAmortizacao,dtUltimaAmortizacao,dtUltimoDesembolsoOriginal,dtUltimoDesembolsoVigente,ano_recebimento
0,60371,PROJETO ALFA/PROJECT ALFA,None,NAN,INSTITUTO INTERNACIONAL PARA SUSTENTABILIDADE ...,Sudeste,Estado do Rio de Janeiro,Federal,Outros,Ch_Inst,...,None,None,None,None,None,None,None,None,None,2017
1,60371,PROJETO ALFA/PROJECT ALFA,None,NAN,INSTITUTO INTERNACIONAL PARA SUSTENTABILIDADE ...,Sudeste,Estado do Rio de Janeiro,Federal,Outros,Ch_Inst,...,None,None,None,None,None,None,None,None,None,2017
2,12761,PROGRAMA DE DESENVOLVIMENTO DO TURISMO NACIONA...,PRODETUR NACIONAL GOIÂNIA,COMÉRCIO E SERVIÇOS (TURISMO),AAA,Centro Oeste,Distrito Federal,Municipal,Operação de Crédito Externo,BID,...,None,None,None,None,None,None,None,None,None,2008
3,59718,APOIO À EXECUÇÃO DA ESTRATÉGIA NACIONAL DE SIM...,DOAÇÃO PRODEV ABDI,FORTALECIMENTO INSTITUCIONAL,AGÊNCIA BRASILEIRA DE DESENVOLVIMENTO INDUSTRI...,Nacional,Distrito Federal,Federal,Doações,BID/PRODEV,...,None,None,None,None,None,None,None,None,None,2009
4,61246,PROGRAMA NOVO SEGURO DE CRÉDITO À EXPORTAÇÃO (...,NSCE,FORTALECIMENTO INSTITUCIONAL,AGÊNCIA BRASILEIRA GESTORA DE FUNDOS GARANTIDO...,Nacional,Distrito Federal,Federal,Operação de Crédito Externo,BID,...,None,None,None,None,None,None,None,None,None,2024

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../database/db.sqlite')

tabelas = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)



print(tabelas)

       name
0  projetos

In [15]:
# Ver estrutura da tabela ( Coluans e tipos ) 
pd.read_sql("PRAGMA table_info(projetos);", conn)

    cid                        name       type  notnull dflt_value  pk
0     0             cdCartaConsulta    INTEGER        0       None   0
1     1                   nmProjeto       TEXT        0       None   0
2     2                   sgProjeto       TEXT        0       None   0
3     3                     nmSetor       TEXT        0       None   0
4     4                   nmSujeito       TEXT        0       None   0
5     5                      Regiao       TEXT        0       None   0
6     6            nmUnidadeFederal       TEXT        0       None   0
7     7       nmAbrangenciaNacional       TEXT        0       None   0
8     8           TipoFinanciamento       TEXT        0       None   0
9     9                     sgFonte       TEXT        0       None   0
10   10                     VlDolar       REAL        0       None   0
11   11                   CpVlDolar       TEXT        0       None   0
12   12                     sgMoeda       TEXT        0       None   0
13   13                      deFase       TEXT        0       None   0
14   14               dtRecebimento  TIMESTAMP        0       None   0
15   15      dtValidadeRecomendacao  TIMESTAMP        0       None   0
16   16         dtReuniaoNegociacao  TIMESTAMP        0       None   0
17   17            dtAprovDiretoria  TIMESTAMP        0       None   0
18   18           dtAprovacaoSenado  TIMESTAMP        0       None   0
19   19           nuResolucaoSenado       TEXT        0       None   0
20   20                dtAssinatura  TIMESTAMP        0       None   0
21   21                  nuoperacao       TEXT        0       None   0
22   22       dtPrimeiraAmortizacao  TIMESTAMP        0       None   0
23   23         dtUltimaAmortizacao  TIMESTAMP        0       None   0
24   24  dtUltimoDesembolsoOriginal       TEXT        0       None   0
25   25   dtUltimoDesembolsoVigente       TEXT        0       None   0
26   26             ano_recebimento    INTEGER        0       None   0